[2025-07-24 06:48:34 +0000] [598467] [INFO] Starting gunicorn 23.0.0
[2025-07-24 06:48:34 +0000] [598467] [INFO] Listening at: http://0.0.0.0:8001 (598467)
[2025-07-24 06:48:34 +0000] [598467] [INFO] Using worker: sync
[2025-07-24 06:48:34 +0000] [598468] [INFO] Booting worker with pid: 598468
[2025-07-24 06:48:34 +0000] [598468] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'QuantumQwerty'
[2025-07-24 06:48:34 +0000] [598468] [INFO] Worker exiting (pid: 598468)
[2025-07-24 06:48:34 +0000] [598467] [ERROR] Worker (pid:598468) exited with code 3
[2025-07-24 06:48:34 +0000] [598467] [ERROR] Shutting down: Master
[2025-07-24 06:48:34 +0000] [598467] [ERROR] Reason: Worker failed to boot.
[2025-07-24 06:49:00 +0000] [598470] [INFO] Starting gunicorn 23.0.0
[2025-07-24 06:49:00 +0000] [598470] [INFO] Listening at: http://0.0.0.0:8001 (598470)
[2025-07-24 06:49:00 +0000] [598470] [INFO] Using worker: sync
[2025-07-24 06:49:00 +0000] [598471] [INFO] Booting worker with pid: 598471
[2025-07-24 06:53:26 +0000] [598470] [CRITICAL] WORKER TIMEOUT (pid:598471)
[2025-07-24 00:53:26 -0600] [598471] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 00:53:26 -0600] [598471] [INFO] Worker exiting (pid: 598471)
[2025-07-24 06:53:26 +0000] [598475] [INFO] Booting worker with pid: 598475
[2025-07-24 06:57:09 +0000] [598470] [CRITICAL] WORKER TIMEOUT (pid:598475)
[2025-07-24 00:57:09 -0600] [598475] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 00:57:09 -0600] [598475] [INFO] Worker exiting (pid: 598475)
[2025-07-24 06:57:09 +0000] [598499] [INFO] Booting worker with pid: 598499
[2025-07-24 06:57:43 +0000] [598470] [CRITICAL] WORKER TIMEOUT (pid:598499)
[2025-07-24 00:57:43 -0600] [598499] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 00:57:43 -0600] [598499] [INFO] Worker exiting (pid: 598499)
[2025-07-24 06:57:43 +0000] [598502] [INFO] Booting worker with pid: 598502
[2025-07-24 07:01:18 +0000] [598470] [CRITICAL] WORKER TIMEOUT (pid:598502)
[2025-07-24 01:01:18 -0600] [598502] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 01:01:18 -0600] [598502] [INFO] Worker exiting (pid: 598502)
[2025-07-24 07:01:18 +0000] [598541] [INFO] Booting worker with pid: 598541
[2025-07-24 07:01:49 +0000] [598470] [CRITICAL] WORKER TIMEOUT (pid:598541)
[2025-07-24 01:01:49 -0600] [598541] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 01:01:49 -0600] [598541] [INFO] Worker exiting (pid: 598541)
[2025-07-24 07:01:49 +0000] [598542] [INFO] Booting worker with pid: 598542
[2025-07-24 07:03:50 +0000] [598470] [INFO] Handling signal: term
[2025-07-24 01:03:50 -0600] [598542] [INFO] Worker exiting (pid: 598542)
[2025-07-24 07:03:50 +0000] [598470] [INFO] Shutting down: Master
[2025-07-24 07:04:10 +0000] [598567] [INFO] Starting gunicorn 23.0.0
[2025-07-24 07:04:10 +0000] [598567] [INFO] Listening at: http://0.0.0.0:8001 (598567)
[2025-07-24 07:04:10 +0000] [598567] [INFO] Using worker: sync
[2025-07-24 07:04:10 +0000] [598568] [INFO] Booting worker with pid: 598568
[2025-07-24 07:04:52 +0000] [598567] [CRITICAL] WORKER TIMEOUT (pid:598568)
[2025-07-24 01:04:52 -0600] [598568] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 01:04:52 -0600] [598568] [INFO] Worker exiting (pid: 598568)
[2025-07-24 07:04:52 +0000] [598570] [INFO] Booting worker with pid: 598570
[2025-07-24 07:05:23 +0000] [598567] [CRITICAL] WORKER TIMEOUT (pid:598570)
[2025-07-24 01:05:23 -0600] [598570] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 01:05:23 -0600] [598570] [INFO] Worker exiting (pid: 598570)
[2025-07-24 07:05:23 +0000] [598571] [INFO] Booting worker with pid: 598571
[2025-07-24 07:06:09 +0000] [598567] [CRITICAL] WORKER TIMEOUT (pid:598571)
[2025-07-24 01:06:09 -0600] [598571] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 01:06:09 -0600] [598571] [INFO] Worker exiting (pid: 598571)
[2025-07-24 07:06:09 +0000] [598574] [INFO] Booting worker with pid: 598574
[2025-07-24 07:10:39 +0000] [598567] [INFO] Handling signal: term
[2025-07-24 01:11:03 -0600] [598574] [INFO] Worker exiting (pid: 598574)
[2025-07-24 07:11:03 +0000] [598567] [INFO] Shutting down: Master
[2025-07-24 07:12:50 +0000] [598624] [INFO] Starting gunicorn 23.0.0
[2025-07-24 07:12:50 +0000] [598624] [INFO] Listening at: http://0.0.0.0:8001 (598624)
[2025-07-24 07:12:50 +0000] [598624] [INFO] Using worker: sync
[2025-07-24 07:12:50 +0000] [598625] [INFO] Booting worker with pid: 598625
[2025-07-24 07:14:03 +0000] [598624] [CRITICAL] WORKER TIMEOUT (pid:598625)
[2025-07-24 01:14:03 -0600] [598625] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 01:14:03 -0600] [598625] [INFO] Worker exiting (pid: 598625)
[2025-07-24 07:14:03 +0000] [599101] [INFO] Booting worker with pid: 599101
[2025-07-24 07:14:53 +0000] [598624] [CRITICAL] WORKER TIMEOUT (pid:599101)
[2025-07-24 01:14:53 -0600] [599101] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 01:14:53 -0600] [599101] [INFO] Worker exiting (pid: 599101)
[2025-07-24 07:14:53 +0000] [599107] [INFO] Booting worker with pid: 599107
[2025-07-24 21:07:34 -0600] [599107] [INFO] Worker exiting (pid: 599107)
[2025-07-25 03:07:34 +0000] [598624] [INFO] Handling signal: term
[2025-07-25 03:07:36 +0000] [598624] [INFO] Shutting down: Master
[2025-07-25 03:10:11 +0000] [600663] [INFO] Starting gunicorn 23.0.0
[2025-07-25 03:10:11 +0000] [600663] [INFO] Listening at: http://0.0.0.0:8001 (600663)
[2025-07-25 03:10:11 +0000] [600663] [INFO] Using worker: sync
[2025-07-25 03:10:11 +0000] [600664] [INFO] Booting worker with pid: 600664
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/qqvenv/QuantumQwerty/Quantum-Qwerty/core/views.py", line 45, in index
    return render(request, 'index.html', {'logos': logos, 'desafios': desafios})
  File "/opt/qqvenv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
Not Found: /favicon.ico
[2025-07-25 03:31:44 +0000] [600663] [INFO] Handling signal: term
[2025-07-24 21:31:44 -0600] [600664] [INFO] Worker exiting (pid: 600664)
[2025-07-25 03:31:45 +0000] [600663] [INFO] Shutting down: Master
[2025-07-25 03:32:39 +0000] [601016] [INFO] Starting gunicorn 23.0.0
[2025-07-25 03:32:39 +0000] [601016] [INFO] Listening at: http://0.0.0.0:8001 (601016)
[2025-07-25 03:32:39 +0000] [601016] [INFO] Using worker: sync
[2025-07-25 03:32:39 +0000] [601017] [INFO] Booting worker with pid: 601017
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/qqvenv/QuantumQwerty/Quantum-Qwerty/core/views.py", line 45, in index
    return render(request, 'index.html', {'logos': logos, 'desafios': desafios})
  File "/opt/qqvenv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
Not Found: /favicon.ico
[2025-07-24 21:34:59 -0600] [601017] [INFO] Worker exiting (pid: 601017)
[2025-07-25 03:34:59 +0000] [601016] [INFO] Handling signal: term
[2025-07-25 03:34:59 +0000] [601016] [INFO] Shutting down: Master
[2025-07-25 03:35:08 +0000] [601029] [INFO] Starting gunicorn 23.0.0
[2025-07-25 03:35:08 +0000] [601029] [INFO] Listening at: http://0.0.0.0:8001 (601029)
[2025-07-25 03:35:08 +0000] [601029] [INFO] Using worker: sync
[2025-07-25 03:35:08 +0000] [601030] [INFO] Booting worker with pid: 601030
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/qqvenv/QuantumQwerty/Quantum-Qwerty/core/views.py", line 45, in index
    return render(request, 'index.html', {'logos': logos, 'desafios': desafios})
  File "/opt/qqvenv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/qqvenv/QuantumQwerty/Quantum-Qwerty/core/views.py", line 45, in index
    return render(request, 'index.html', {'logos': logos, 'desafios': desafios})
  File "/opt/qqvenv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/qqvenv/QuantumQwerty/Quantum-Qwerty/core/views.py", line 45, in index
    return render(request, 'index.html', {'logos': logos, 'desafios': desafios})
  File "/opt/qqvenv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/qqvenv/QuantumQwerty/Quantum-Qwerty/core/views.py", line 45, in index
    return render(request, 'index.html', {'logos': logos, 'desafios': desafios})
  File "/opt/qqvenv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/opt/qqvenv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[2025-07-25 03:36:02 +0000] [601029] [CRITICAL] WORKER TIMEOUT (pid:601030)
[2025-07-24 21:36:02 -0600] [601030] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 21:36:02 -0600] [601030] [INFO] Worker exiting (pid: 601030)
[2025-07-25 03:36:02 +0000] [601032] [INFO] Booting worker with pid: 601032
[2025-07-24 21:53:30 -0600] [601032] [INFO] Worker exiting (pid: 601032)
[2025-07-25 03:53:30 +0000] [601029] [INFO] Handling signal: term
[2025-07-25 03:53:30 +0000] [601029] [ERROR] Worker (pid:601032) was sent SIGTERM!
[2025-07-25 03:53:30 +0000] [601029] [INFO] Shutting down: Master
[2025-07-25 03:53:43 +0000] [601102] [INFO] Starting gunicorn 23.0.0
[2025-07-25 03:53:43 +0000] [601102] [INFO] Listening at: http://0.0.0.0:8001 (601102)
[2025-07-25 03:53:43 +0000] [601102] [INFO] Using worker: sync
[2025-07-25 03:53:43 +0000] [601103] [INFO] Booting worker with pid: 601103
Requested Range Not Satisfiable: /static/img/instagram_color_qq.png
[2025-07-25 04:01:47 +0000] [601102] [CRITICAL] WORKER TIMEOUT (pid:601103)
[2025-07-24 22:01:47 -0600] [601103] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:01:47 -0600] [601103] [INFO] Worker exiting (pid: 601103)
[2025-07-25 04:01:47 +0000] [601109] [INFO] Booting worker with pid: 601109
[2025-07-25 04:04:42 +0000] [601102] [INFO] Handling signal: term
[2025-07-25 04:05:00 +0000] [601141] [INFO] Starting gunicorn 23.0.0
[2025-07-25 04:05:00 +0000] [601141] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2025-07-25 04:05:00 +0000] [601141] [ERROR] connection to ('0.0.0.0', 8001) failed: [Errno 98] Address already in use
[2025-07-25 04:05:01 +0000] [601141] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2025-07-25 04:05:01 +0000] [601141] [ERROR] connection to ('0.0.0.0', 8001) failed: [Errno 98] Address already in use
[2025-07-25 04:05:02 +0000] [601141] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2025-07-25 04:05:02 +0000] [601141] [ERROR] connection to ('0.0.0.0', 8001) failed: [Errno 98] Address already in use
[2025-07-25 04:05:03 +0000] [601141] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2025-07-25 04:05:03 +0000] [601141] [ERROR] connection to ('0.0.0.0', 8001) failed: [Errno 98] Address already in use
[2025-07-25 04:05:04 +0000] [601141] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2025-07-25 04:05:04 +0000] [601141] [ERROR] connection to ('0.0.0.0', 8001) failed: [Errno 98] Address already in use
[2025-07-25 04:05:05 +0000] [601141] [ERROR] Can't connect to ('0.0.0.0', 8001)
[2025-07-25 04:05:12 +0000] [601102] [INFO] Shutting down: Master
[2025-07-25 04:05:53 +0000] [601146] [INFO] Starting gunicorn 23.0.0
[2025-07-25 04:05:53 +0000] [601146] [INFO] Listening at: http://0.0.0.0:8001 (601146)
[2025-07-25 04:05:53 +0000] [601146] [INFO] Using worker: sync
[2025-07-25 04:05:53 +0000] [601147] [INFO] Booting worker with pid: 601147
[2025-07-25 04:08:24 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601147)
[2025-07-24 22:08:24 -0600] [601147] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:08:24 -0600] [601147] [INFO] Worker exiting (pid: 601147)
[2025-07-25 04:08:24 +0000] [601151] [INFO] Booting worker with pid: 601151
[2025-07-25 04:08:59 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601151)
[2025-07-24 22:08:59 -0600] [601151] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:08:59 -0600] [601151] [INFO] Worker exiting (pid: 601151)
[2025-07-25 04:08:59 +0000] [601157] [INFO] Booting worker with pid: 601157
[2025-07-25 04:09:30 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601157)
[2025-07-24 22:09:30 -0600] [601157] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:09:30 -0600] [601157] [INFO] Worker exiting (pid: 601157)
[2025-07-25 04:09:31 +0000] [601159] [INFO] Booting worker with pid: 601159
[2025-07-25 04:10:41 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601159)
[2025-07-24 22:10:41 -0600] [601159] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:10:41 -0600] [601159] [INFO] Worker exiting (pid: 601159)
[2025-07-25 04:10:41 +0000] [601160] [INFO] Booting worker with pid: 601160
[2025-07-25 04:12:45 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601160)
[2025-07-24 22:12:45 -0600] [601160] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:12:45 -0600] [601160] [INFO] Worker exiting (pid: 601160)
[2025-07-25 04:12:45 +0000] [601163] [INFO] Booting worker with pid: 601163
[2025-07-25 04:13:16 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601163)
[2025-07-24 22:13:16 -0600] [601163] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:13:16 -0600] [601163] [INFO] Worker exiting (pid: 601163)
[2025-07-25 04:13:16 +0000] [601164] [INFO] Booting worker with pid: 601164
[2025-07-25 04:14:12 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601164)
[2025-07-24 22:14:12 -0600] [601164] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:14:12 -0600] [601164] [INFO] Worker exiting (pid: 601164)
[2025-07-25 04:14:12 +0000] [601167] [INFO] Booting worker with pid: 601167
[2025-07-25 04:15:23 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601167)
[2025-07-24 22:15:23 -0600] [601167] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:15:23 -0600] [601167] [INFO] Worker exiting (pid: 601167)
[2025-07-25 04:15:23 +0000] [601169] [INFO] Booting worker with pid: 601169
[2025-07-25 04:16:08 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601169)
[2025-07-24 22:16:08 -0600] [601169] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:16:08 -0600] [601169] [INFO] Worker exiting (pid: 601169)
[2025-07-25 04:16:08 +0000] [601171] [INFO] Booting worker with pid: 601171
[2025-07-25 04:16:50 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601171)
[2025-07-24 22:16:50 -0600] [601171] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:16:50 -0600] [601171] [INFO] Worker exiting (pid: 601171)
[2025-07-25 04:16:50 +0000] [601173] [INFO] Booting worker with pid: 601173
[2025-07-25 04:17:30 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601173)
[2025-07-24 22:17:30 -0600] [601173] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:17:30 -0600] [601173] [INFO] Worker exiting (pid: 601173)
[2025-07-25 04:17:30 +0000] [601177] [INFO] Booting worker with pid: 601177
[2025-07-25 04:18:34 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601177)
[2025-07-24 22:18:34 -0600] [601177] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:18:34 -0600] [601177] [INFO] Worker exiting (pid: 601177)
[2025-07-25 04:18:34 +0000] [601178] [INFO] Booting worker with pid: 601178
[2025-07-25 04:36:41 +0000] [601146] [CRITICAL] WORKER TIMEOUT (pid:601178)
[2025-07-24 22:36:41 -0600] [601178] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/opt/qqvenv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-07-24 22:36:41 -0600] [601178] [INFO] Worker exiting (pid: 601178)
[2025-07-25 04:36:41 +0000] [601221] [INFO] Booting worker with pid: 601221
[2025-07-25 04:48:02 +0000] [601146] [INFO] Handling signal: term
[2025-07-24 22:48:02 -0600] [601221] [INFO] Worker exiting (pid: 601221)
[2025-07-25 04:48:02 +0000] [601146] [ERROR] Worker (pid:601221) was sent SIGTERM!
[2025-07-25 04:48:02 +0000] [601146] [INFO] Shutting down: Master
[2025-07-25 04:48:54 +0000] [601291] [INFO] Starting gunicorn 23.0.0
[2025-07-25 04:48:54 +0000] [601291] [INFO] Listening at: http://0.0.0.0:8001 (601291)
[2025-07-25 04:48:54 +0000] [601291] [INFO] Using worker: sync
[2025-07-25 04:48:54 +0000] [601292] [INFO] Booting worker with pid: 601292
[2025-07-24 23:10:41 -0600] [601292] [INFO] Worker exiting (pid: 601292)
[2025-07-25 05:10:41 +0000] [601291] [INFO] Handling signal: term
[2025-07-25 05:10:41 +0000] [601291] [INFO] Shutting down: Master
[2025-07-25 05:11:11 +0000] [601411] [INFO] Starting gunicorn 23.0.0
[2025-07-25 05:11:11 +0000] [601411] [INFO] Listening at: http://0.0.0.0:8001 (601411)
[2025-07-25 05:11:11 +0000] [601411] [INFO] Using worker: sync
[2025-07-25 05:11:11 +0000] [601412] [INFO] Booting worker with pid: 601412
[2025-07-24 23:12:36 -0600] [601412] [INFO] Worker exiting (pid: 601412)
[2025-07-25 05:12:36 +0000] [601411] [INFO] Handling signal: term
[2025-07-25 05:12:36 +0000] [601411] [INFO] Shutting down: Master
[2025-07-25 05:13:01 +0000] [601433] [INFO] Starting gunicorn 23.0.0
[2025-07-25 05:13:01 +0000] [601433] [INFO] Listening at: http://0.0.0.0:8001 (601433)
[2025-07-25 05:13:01 +0000] [601433] [INFO] Using worker: sync
[2025-07-25 05:13:01 +0000] [601434] [INFO] Booting worker with pid: 601434
[2025-07-24 23:15:15 -0600] [601434] [INFO] Worker exiting (pid: 601434)
[2025-07-25 05:15:15 +0000] [601433] [INFO] Handling signal: term
[2025-07-25 05:15:15 +0000] [601433] [ERROR] Worker (pid:601434) was sent SIGTERM!
[2025-07-25 05:15:15 +0000] [601433] [INFO] Shutting down: Master
[2025-07-25 05:15:39 +0000] [601455] [INFO] Starting gunicorn 23.0.0
[2025-07-25 05:15:39 +0000] [601455] [INFO] Listening at: http://0.0.0.0:8001 (601455)
[2025-07-25 05:15:39 +0000] [601455] [INFO] Using worker: sync
[2025-07-25 05:15:39 +0000] [601456] [INFO] Booting worker with pid: 601456
[2025-07-24 23:18:23 -0600] [601456] [INFO] Worker exiting (pid: 601456)
[2025-07-25 05:18:23 +0000] [601455] [INFO] Handling signal: term
[2025-07-25 05:18:23 +0000] [601455] [INFO] Shutting down: Master
[2025-07-25 05:18:32 +0000] [601482] [INFO] Starting gunicorn 23.0.0
[2025-07-25 05:18:32 +0000] [601482] [INFO] Listening at: http://0.0.0.0:8001 (601482)
[2025-07-25 05:18:32 +0000] [601482] [INFO] Using worker: sync
[2025-07-25 05:18:32 +0000] [601483] [INFO] Booting worker with pid: 601483
[2025-07-24 23:26:45 -0600] [601483] [INFO] Worker exiting (pid: 601483)
[2025-07-25 05:26:45 +0000] [601482] [INFO] Handling signal: term
[2025-07-25 05:26:45 +0000] [601482] [INFO] Shutting down: Master
[2025-07-25 05:27:00 +0000] [601795] [INFO] Starting gunicorn 23.0.0
[2025-07-25 05:27:00 +0000] [601795] [INFO] Listening at: http://0.0.0.0:8001 (601795)
[2025-07-25 05:27:00 +0000] [601795] [INFO] Using worker: sync
[2025-07-25 05:27:00 +0000] [601796] [INFO] Booting worker with pid: 601796
Not Found: /asdfags
Not Found: /favicon.ico
[2025-07-24 23:28:21 -0600] [601796] [INFO] Worker exiting (pid: 601796)
[2025-07-25 05:28:21 +0000] [601795] [INFO] Handling signal: term
[2025-07-25 05:28:21 +0000] [601795] [INFO] Shutting down: Master
[2025-07-25 05:28:27 +0000] [601809] [INFO] Starting gunicorn 23.0.0
[2025-07-25 05:28:27 +0000] [601809] [INFO] Listening at: http://0.0.0.0:8001 (601809)
[2025-07-25 05:28:27 +0000] [601809] [INFO] Using worker: sync
[2025-07-25 05:28:27 +0000] [601810] [INFO] Booting worker with pid: 601810
Not Found: /favicon.ico
Not Found: /web-app-manifest-512x512.png
Not Found: /web-app-manifest-512x512.png
Not Found: /web-app-manifest-512x512.png
Not Found: /web-app-manifest-512x512.png
Not Found: /web-app-manifest-512x512.png
Not Found: /web-app-manifest-192x192.png
Not Found: /web-app-manifest-192x192.png
Not Found: /web-app-manifest-192x192.png
Not Found: /web-app-manifest-512x512.png
Not Found: /web-app-manifest-512x512.png
Not Found: /web-app-manifest-192x192.png
Not Found: /web-app-manifest-192x192.png
Not Found: /web-app-manifest-512x512.png
Not Found: /web-app-manifest-512x512.png
Forbidden (Origin checking failed - https://quantumqwerty.com does not match any trusted origins.): /ContactUs/
Forbidden (Origin checking failed - https://quantumqwerty.com does not match any trusted origins.): /ContactUs/
Not Found: /favicon.ico
Not Found: /web-app-manifest-512x512.png
Forbidden (Origin checking failed - https://quantumqwerty.com does not match any trusted origins.): /ContactUs/
Not Found: /robots.txt
Not Found: /robots.txt
[2025-07-25 06:09:37 +0000] [601809] [INFO] Handling signal: term
[2025-07-25 00:09:37 -0600] [601810] [INFO] Worker exiting (pid: 601810)
[2025-07-25 06:09:37 +0000] [601809] [INFO] Shutting down: Master
[2025-07-25 06:10:35 +0000] [601980] [INFO] Starting gunicorn 23.0.0
[2025-07-25 06:10:35 +0000] [601980] [INFO] Listening at: http://0.0.0.0:8001 (601980)
[2025-07-25 06:10:35 +0000] [601980] [INFO] Using worker: sync
[2025-07-25 06:10:35 +0000] [601981] [INFO] Booting worker with pid: 601981
Forbidden (Origin checking failed - https://quantumqwerty.com does not match any trusted origins.): /ContactUs/
Forbidden (Origin checking failed - https://quantumqwerty.com does not match any trusted origins.): /ContactUs/
Forbidden (Origin checking failed - https://quantumqwerty.com does not match any trusted origins.): /ContactUs/
Not Found: /']
[2025-07-25 00:24:48 -0600] [601981] [INFO] Worker exiting (pid: 601981)
[2025-07-25 06:24:48 +0000] [601980] [INFO] Handling signal: term
[2025-07-25 06:24:48 +0000] [601980] [INFO] Shutting down: Master
[2025-07-25 06:24:53 +0000] [602093] [INFO] Starting gunicorn 23.0.0
[2025-07-25 06:24:53 +0000] [602093] [INFO] Listening at: http://0.0.0.0:8001 (602093)
[2025-07-25 06:24:53 +0000] [602093] [INFO] Using worker: sync
[2025-07-25 06:24:53 +0000] [602094] [INFO] Booting worker with pid: 602094
Forbidden (Origin checking failed - https://quantumqwerty.com does not match any trusted origins.): /ContactUs/
